[build]
distDir = "../frontend/dist"
devPath = "http://localhost:8080"
beforeDevCommand = "cd frontend && trunk serve"
beforeBuildCommand = "cd frontend && trunk build"
withGlobalTauri = true

[package]
productName = "rsty_stack_test"
version = "0.1.0"

[tauri.allowlist]
all = false

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = [ ]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "com.rstystacktest.app"
longDescription = ""
resources = [ ]
shortDescription = ""
targets = "all"

  [tauri.bundle.deb]
  depends = [ ]

  [tauri.bundle.macOS]
  exceptionDomain = ""
  frameworks = [ ]

  [tauri.bundle.windows]
  digestAlgorithm = "sha256"
  timestampUrl = ""

[tauri.security]

[tauri.updater]
active = false

[[tauri.windows]]
fullscreen = false
height = 600
resizable = true
title = "RSTY_APP"
width = 800